---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1662612/public_html/code.zelnara.com
    - /bin/cp -R $SOURCE_DIR/* $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/vendor
    - /usr/bin/composer install --no-dev --optimize-autoloader -d $DEPLOYPATH
    - /usr/bin/php $DEPLOYPATH/artisan migrate --force
    - /usr/bin/php $DEPLOYPATH/artisan cache:clear
    - /usr/bin/php $DEPLOYPATH/artisan config:cache
    - /usr/bin/php $DEPLOYPATH/artisan route:cache
    - /usr/bin/php $DEPLOYPATH/artisan view:cache
